name: github-workflow-testautomation
run-name: ${{ github.actor }} is running the workflow
on: [push]

defaults:
  run:
    shell: bash
    working-directory: scripts
jobs:
  the_first_test:
    name: The First Test Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: python version 3.* set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: updating pip, requirements, pytest
        run: python -m pip install --upgrade pip
             pip install -r requirements.txt
             pip install pytest

      - name: running test file with pytest
        run: pytest test_pyfarmsay.py

      - name: upload pytest results
        uses: actions/upload-artifact@v3
        with:
          name: pytest results of the run
          path: junit/test-results.xml
        if: ${{ always() }}