name: pyfarm-test
run-name: ${{ github.actor }}'s Pull Request Run of the Workflow
on: [pull_request]

jobs:
  the_first_test:
    name: The First Test Job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    #envirnoment variable CI set to false

    steps:
      - uses: actions/checkout@v3
      - name: python version 3.* set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: updating pip, requirements, pytest
        run: | 
            python -m pip install --upgrade pip
            pip install pytest

      - name: Turning 'editable' mode on
        run: pip install -e .
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: creating pytest directory
        run: mkdir -p tests/test_results/
        
      - name: running test file with pytest
        run: python -m pytest ./tests/test.py
        continue-on-error: true

     
      - name: upload pytest results
        uses: actions/upload-artifact@v3
        with:
          name: pytest results of the run
          path: ./.github/test_results/test-results.xml
        if: ${{ always() }}


#discord-notify:
  #name: Pull Request Notification
  #nvm no discord notification due to lack of permissions

